FROM golang:1.23 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /app/rattle ./cmd/fiber-server

FROM alpine:latest

COPY --from=builder /app/rattle /usr/local/bin/rattle

EXPOSE ${FIBER_PORT}

ENTRYPOINT ["rattle"]