version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: rattle_postgres
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5435:${POSTGRES_PORT:-5432}"
    volumes:
      - ${POSTGRES_VOLUMES}
    networks:
      - rattle-network

  scanner:
    build:
      context: https://github.com/ilyxenc/rattle.git
      dockerfile: Dockerfile.scanner
    container_name: rattle_scanner
    depends_on:
      - postgres
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - rattle-network

  fiber-server:
    build:
      context: https://github.com/ilyxenc/rattle.git
      dockerfile: Dockerfile.fiber-server
    container_name: rattle_fiber_server
    depends_on:
      - postgres
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${FIBER_PORT:-3000}:${FIBER_PORT:-3000}"
    networks:
      - rattle-network

  frontend:
    build:
      context: https://github.com/ilyxenc/rattle-frontend.git
      dockerfile: Dockerfile
    container_name: rattle_frontend
    restart: always
    env_file:
      - .env
    ports:
      - "${PORT:-3001}:${PORT:-3001}"
    networks:
      - rattle-network

volumes:
  pgdata:

networks:
  rattle-network:
    driver: bridge
