name: Build and Push Docker Images

on:
  push:
    tags:
      - 'v*.*.*'

env:
  REGISTRY: ghcr.io
  REPO: ${{ github.repository }}

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - name: scanner
            dockerfile: Dockerfile.scanner
          - name: server
            dockerfile: Dockerfile.server
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push ${{ matrix.name }} Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.REGISTRY }}/${{ env.REPO }}-${{ matrix.name }}:${{ github.ref_name }}
            ${{ env.REGISTRY }}/${{ env.REPO }}-${{ matrix.name }}:latest
